version: "3"

services:
  vscode:
    build: .
    image: latexdevcontainer
    user: 1000:1000
    volumes:
      - ../:/workspace
      # SSH directory
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      # Git config
      - ~/.gitconfig:/home/districter/.gitconfig
      - ~/.gitconfig:/root/.gitconfig
    entrypoint: /bin/bash -c "while sleep 1000; do :; done"